---
title: "Untitled"
format: html
editor: visual
---

## Quarto

```{r}
logEPPF_DP <- function(alpha, n, k) {
  # Loglikelihood
  loglik <- k * log(alpha) - lgamma(alpha + n) + lgamma(alpha)
  loglik
}

max_EPPF_DP <- function(n, k) {
  start <- 1 # Initialization of the maximization algorithm
  out <- nlminb(
    start = start,
    function(param) -logEPPF_DP(alpha = param, n = n, k = k),
    lower = 1e-10, upper = Inf
  )
  return(out$par)
}
max_EPPF_DP <- Vectorize(max_EPPF_DP, vectorize.args = c("n", "k"))

```

## Running Code

```{r}
g_inv <- function(mu_target, size) {
    if (mu_target <= 1) {
      return(1e-7)
    } else if (mu_target >= size) {
      return(1e8)
    } else {
      uniroot(function(x) x * (digamma(x + size) - digamma(x)) - mu_target, c(1e-10, 1e8), tol = 1e-8)$root
    }
  }
g_inv <- Vectorize(g_inv, vectorize.args = c("mu_target", "size"))
  
fisher_NR <- function(X, y, n, tol = 1e-16, beta_start = NULL, maxiter = 10000) {
  g_inv <- function(mu_target, size) {
    if (mu_target <= 1) {
      return(1e-7)
    } else if (mu_target >= size) {
      return(1e8)
    } else {
      uniroot(function(x) x * (digamma(x + size) - digamma(x)) - mu_target, c(1e-10, 1e8), tol = 1e-8)$root
    }
  }
  g_inv <- Vectorize(g_inv, vectorize.args = c("mu_target", "size"))

  loglik <- numeric(maxiter)

  # Initialization
  mu <- y # c(X %*% solve(crossprod(X), crossprod(X, y)))
  alpha <- g_inv(mu, n)
  eta <- log(alpha)
  w <- mu + alpha^2 * (trigamma(alpha + n) - trigamma(alpha))
  z <- eta + (y - mu) / w

  # First value of the likelihood
  loglik[1] <- sum(y * eta - lgamma(alpha + n) + lgamma(alpha))

  # Iterative procedure
  for (t in 2:maxiter) {
    beta <- solve(qr(crossprod(X * w, X)), crossprod(X * w, z))
    eta <- c(X %*% beta)
    alpha <- exp(eta)
    mu <- alpha * (digamma(alpha + n) - digamma(alpha))
    w <- mu + alpha^2 * (trigamma(alpha + n) - trigamma(alpha))
    z <- eta + (y - mu) / w

    loglik[t] <- sum(y * eta - lgamma(alpha + n) + lgamma(alpha))
    if (abs(loglik[t] - loglik[t - 1]) < tol) {
      break
    } 
    #stop("The algorithm has not reached convergence")
  }
  # Calculate fisher info and pvalues
  Fisher_info <- solve(t(X) %*% diag(w) %*% X)
  t_vals <- beta/sqrt(diag(Fisher_info))
  p_vals <- 2 * pnorm(-abs(t_vals))
  # Output the results
  results <- list(beta = cbind(beta = beta, 
                               t_vals = t_vals,
                               p_vals = p_vals), 
                  vcov = Fisher_info,
                  Convergence = cbind(Iteration = (1:t) - 1, Loglikelihood = loglik[1:t]))
  return(results)
}
```

```{r}
# Functions to compute the mean and the variance
#polyseries_mean <- Vectorize(polyseries_mean_cpp, vectorize.args = c("size", "alpha"))
#polyseries_var <- Vectorize(polyseries_var_cpp, vectorize.args = c("size", "alpha"))

Hubbell_NR <- function(X, y, n, sigma = 0, tol = 1e-16, beta_start = NULL, maxiter = 10000) {
polyseries_mean <- Vectorize(HubbellGLM:::polyseries_mean_cpp, vectorize.args =c("size", "alpha"))
polyseries_var <- Vectorize(HubbellGLM:::polyseries_var_cpp, vectorize.args = c("size", "alpha"))

  g_inv <- function(mu_target, size, sigma) {
    if (mu_target <= 1) {
      return(1e-7)
    } else if (mu_target >= size) {
      return(1e8)
    } else {
      uniroot(function(x) polyseries_mean(size, x, sigma) - mu_target, c(1e-10, 1e8), tol = 1e-8)$root
    }
  }
  g_inv <- Vectorize(g_inv, vectorize.args = c("mu_target", "size"))

  loglik <- numeric(maxiter)

  # Initialization (If null, implicitely initialized at beta=0)

  # Initialization
  mu <- y # c(X %*% solve(crossprod(X), crossprod(X, y)))
  alpha <- g_inv(mu, n, sigma = sigma)
  eta <- log(alpha)
  w <- mu + alpha^2 * (trigamma(alpha + n) - trigamma(alpha))
  z <- eta + (y - mu) / w

  # First value of the likelihood
  loglik[1] <- sum(y * eta - lgamma(alpha + n) + lgamma(alpha))

  # Iterative procedure
  for (t in 2:maxiter) {
    # Find coefficients
    beta <- solve(qr(crossprod(X * w, X)), crossprod(X * w, z))
    eta <- c(X %*% beta)
    exp_eta <- exp(eta)
    # Calculate the mean
    mu <- polyseries_mean(size = n, alpha = exp_eta, sigma = sigma)
    # Calculate the variance of the distribution
    alpha <- g_inv(mu, n, sigma = 0)
    v <- alpha * (digamma(alpha + n) - digamma(alpha)) + alpha^2 * (trigamma(alpha + n) - trigamma(alpha))
    # Calculate glm weights
    w <- (1 / v) * polyseries_var(size =  n, alpha = exp_eta, sigma = sigma) ^ 2 
    # Calculate linearized response
    z <- eta + (y - mu) / sqrt(w * v)
    # Update loglikelihood
    loglik[t] <- sum(y * log(alpha) - lgamma(alpha + n) + lgamma(alpha))
    if (abs(loglik[t] - loglik[t - 1]) < tol) {
      break
    } 
    #stop("The algorithm has not reached convergence")
  }
  # Calculate fisher info and pvalues
  Fisher_info <- solve(t(X) %*% diag(w) %*% X)
  t_vals <- beta/sqrt(diag(Fisher_info))
  p_vals <- 2 * pnorm(-abs(t_vals))
  # Output the results
  results <- list(beta = cbind(beta = beta, 
                               t_vals = t_vals,
                               p_vals = p_vals), 
                  vcov = Fisher_info,
                  Convergence = cbind(Iteration = (1:t) - 1, Loglikelihood = loglik[1:t]))
  return(results)
}
```

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
BarroColorado

fit <- HubbellGLM(cbind(n, y) ~ ., data = BarroColorado)

# Run the experiment to replicate data
simulate_data <- function(N, p, lambda){
  X <- cbind(1, matrix(rnorm(N * (p - 1), sd = 10), nrow = N, ncol = p - 1))
  beta <- c(2, rnorm(p-1, sd = 0.1))
  alphas <- exp(X %*% beta)
  n <- rpois(N, lambda = lambda)
  y <- rDPspecies(alpha = alphas, size = n)
  return(list(n = n, y = y, beta = beta, X = X, df = data.frame(n = n, y = y, X)))
}


# Try the function
set.seed(10)
data <- simulate_data(N = 1200, p = 10, lambda = 1000)
data$beta

fit <- HubbellGLM(cbind(n, y) ~ .-1, data = data$df)
summary(fit)
family(fit)
predict(fit, type = "response")
predict(fit, newdata = BarroColorado[41:50, ], type = "response")


predict(fit, type = "link", se.fit = TRUE)
summary(fit)

vcov(fit)
```

```{r}
X <- model.matrix(y ~ . - n, data = BarroColorado)
y <- BarroColorado$y
n <- BarroColorado$n
res <- fisher_NR(X = X, y = y, n = n, tol = 1e-13)

cbind(res$beta, coef(fit))

fit <- HubbellGLM(cbind(n, y) ~ ., data = BarroColorado)
fitPois <- glm(y ~ . - n,
  offset = log(-digamma(1) + log(n)), family = poisson,
  data = BarroColorado %>% dplyr::mutate(y = y - 1)
)

sqrt(sum((predict(fitPois, type = "response") + 1 - y)^2))
sqrt(sum((predict(fit, type = "response") - y)^2))
cbind(coef(fit), coef(fitPois))

summary(fit)
summary(fitPois)

plot(predict(fit, type = "response"), predict(fitPois, type = "response") + 1)
abline(a = 0, b = 1)
```

```{r}
nmax <- rpois(n = length(y), 10000)
fit <- HubbellGLM(cbind(nmax, y) ~ . - n, data = BarroColorado)
fitPois <- glm(y ~ . - n,
  offset = log(-digamma(1) + log(n)),
  family = poisson, data = BarroColorado %>% dplyr::mutate(y = y - 1, n = nmax)
)
plot(coef(fit), coef(fitPois))
abline(a = 0, b = 1)
cbind(coef(fit), coef(fitPois))


sqrt(sum((predict(fit, type = "response") - y)^2))
sqrt(sum((predict(fitPois, type = "response") - y)^2))


predict(fitPois, type = "response")

plot(predict(fit, type = "response"), predict(fitPois, type = "response"))
fit$aic
fitPois$aic
deviance(fit)
deviance(fitPois)
```

# First thing to sort out: how different are we from the two stage approach?

```{r}
# Usign Barro Colorado island
fit <- HubbellGLM(cbind(n, y) ~., data = BarroColorado)
summary(fit)

# Using two-stage approach. First find Fisher's alpha, then run ML
alpha_fisher <- vegan::fisher.alpha(BCI) 
alpha_DP <- max_EPPF_DP(n = BarroColorado$n, k = BarroColorado$y)
X <- model.matrix(cbind(n, y) ~., data = BarroColorado)
fit_twostage <- lm(log(alpha_DP) ~  X - 1)
cbind("HubbellGLM" = coef(fit), "lm_log_alpha" = coef(fit_twostage))

summary(fit)
summary(fit_twostage)
# Values are exactly the same. We need to understand if there is a further relationship under more general links, or if this is just for the canonical link.
```

```{r}
# Try the polyseries
X <- model.matrix(y ~ . - n, data = BarroColorado)
y <- BarroColorado$y
n <- BarroColorado$n
res_log <- fisher_NR(X = X, y = y, n = n, tol = 1e-13)

res_log$beta
fit <- HubbellGLM(cbind(n, y) ~., data = BarroColorado)
summary(fit)
res_log$beta



cbind(res_log$beta[, 1], res_hub$beta[, 1])

g_inv_hub <- function(mu_target, size, sigma) {
    if (mu_target <= 1) {
      return(1e-7)
    } else if (mu_target >= size) {
      return(1e8)
    } else {
      uniroot(function(x) polyseries_mean(size, x, sigma) - mu_target, c(1e-10, 1e8))$root
    }
}
g_inv_hub <- Vectorize(g_inv_hub, vectorize.args = c("mu_target", "size"))

sigma <- 0.1
res_hub <- Hubbell_NR(X = X, y = y, n = n, sigma = sigma, tol = 1e-13)
#res_hub$Convergence
res_hub$beta[,1]

alpha_tent <- g_inv_hub(y, size = n, sigma = sigma)
temp <- lm(log(alpha_tent) ~ X-1)#, offset = -rep(log(sigma), nrow(X))))

cbind(res_hub$beta[,1], temp$coefficients[, 1])
```

```{r}
# Try the polyseries link

# Model paraeters
X <- model.matrix(y ~ . - n, data = BarroColorado)
y <- BarroColorado$y
n <- BarroColorado$n

sigma <- 0
# HubbellNR
res_fisher <- fisher_NR(X, y, n, tol = 1e-13)
res_nr <- Hubbell_NR(X, y, n, sigma, tol = 1e-13)

# Fit GLM
fit <- HubbellGLM(cbind(n, y) ~ ., data = BarroColorado)
#summary(fit)

# Fit GLM poly
fit.poly <- HubbellGLMpoly(cbind(n, y) ~ ., 
                           family = hubbell.poly(sigma = sigma), 
                           data = BarroColorado)

#summary(fit.poly)
#summary(fit)

res <- cbind(glm_dp = fit$coefficients, 
             glm_poly = fit.poly$coefficients, 
             manual_dp = res_fisher$beta[, 1],
             manual_poly = res_nr$beta[, 1])
res
res
summary(fit.poly)

logLik(fit.poly)
logLik(fit)

res_fisher$Convergence
res_nr$Convergence

max_EPPF_DP(n[1], y[1])
res
exp(res[1, ])

```

```{r}
sigma_range <- seq(-1, 0.9, 0.05)

aic_all <- sapply(sigma_range, function(sigma) {
  print(sigma)
  fit.poly <- HubbellGLMpoly(cbind(n, y) ~., 
                           family = hubbell.poly(sigma = sigma), 
                           data = BarroColorado)
  c(aic = AIC(fit.poly), rmse = sqrt(mean((predict.HubbellGLMpoly(fit.poly, type = "response") - BarroColorado$y)^2)))
})

sigma_range[which.min(aic_all[1, ])]



library(vegan)
data(BCI)
S <- specnumber(BCI) # observed number of species
(raremax <- min(rowSums(BCI)))
Srare <- rareslope(BCI, raremax)

abundances <- BCI

rarefy <- function(abundances){
  abundances <- abundances[abundances > 0]
  c(rarefy_C(abundances, sum(abundances), length(abundances), FALSE))
}

Delta_log_rarefy <- function(abundances){
  rar <- rarefy(abundances)
  diff(log(rar))#/diff(rar)
}

Deltas <- apply(BCI, 1, function(x) Delta_log_rarefy(x))
res <- lapply(Deltas, function(x) {
  S <- 1:(length(x))
  c(sum(x/S), sum(1/S^2))
})
res <- do.call("rbind", res)
sum(res[, 1])/sum(res[, 2])


x <- Deltas[[1]]
plot(x, type = "l")
lines(1/1:(length(x)))

plot()
```

```{r}
AIC(fit.poly)
AIC(fit)
plot(predict.HubbellGLMpoly(fit.poly, type = "response"), y)
plot(predict.HubbellGLM(fit, type = "response"), y)
plot(predict.HubbellGLMpoly(fit.poly, type = "response"), predict.HubbellGLM(fit, type = "response"))
abline(a = 0, b =1)
predict.HubbellGLMpoly(fit.poly)
fitglm <- glm(cbind(y, n - y) ~ ., data = BarroColorado, family = "binomial")
summary(fitglm)
logit <- function(p) log(p/(1-p))
fitlm <- lm(logit(y/n) ~ .,  data = BarroColorado)
cbind(fitglm$coefficients, fitlm$coefficients)
```

```{r}
# Verify last thing in simulation. Do we recove the polynomial growth?
simulate_data <- function(N, p, lambda, sigma = 0){
  X <- cbind(1, matrix(rnorm(N * (p - 1), sd = 10), nrow = N, ncol = p - 1))
  n <- rpois(N, lambda = lambda)
  beta <- c(2, rnorm(p-1, sd = 0.1))
  exp_eta <- exp(X %*% beta)
  polyseries_mean <- Vectorize(HubbellGLM:::polyseries_mean_cpp, vectorize.args =c("size", "alpha"))
  mu <- polyseries_mean(n, exp_eta, sigma  = sigma)
  # Find associated alphas
  alphas <- g_inv(mu, n)
  y <- rDPspecies(alpha = alphas, size = n)
  return(list(n = n, y = y, 
              beta = beta, X = X, 
              sigma= sigma, 
              df = data.frame(n = n, y = y, X)))
}

# Try the function
set.seed(10)
data <- simulate_data(N = 1000, p = 10, lambda = 1000, sigma = 0.1)

temp_m <- Hubbell_NR(X = data$X, y = data$y, n = data$n, sigma = -0.5)
temp0 <- Hubbell_NR(X = data$X, y = data$y, n = data$n, sigma = 0)
temp1 <- Hubbell_NR(X = data$X, y = data$y, n = data$n, sigma = 0.1)
temp2 <- Hubbell_NR(X = data$X, y = data$y, n = data$n, sigma = 0.2)
temp3 <- Hubbell_NR(X = data$X, y = data$y, n = data$n, sigma = 0.3)

rbind(cbind(tail(temp_m$Convergence, 1), sigma = -0.5), 
      cbind(tail(temp0$Convergence, 1), sigma = 0),
      cbind(tail(temp1$Convergence, 1), sigma = 0.1),
      cbind(tail(temp2$Convergence, 1), sigma = 0.2),
      cbind(tail(temp3$Convergence, 1), sigma = 0.3))

fit_sim <- HubbellGLMpoly(cbind(n, y) ~ . -1, data = data$df, family =hubbell.poly(sigma=0.1))
summary(fit_sim)

data$df

res_sim <- Hubbell_NR(data$X, data$y, data$n, 0)
res_sim

cbind(res_sim$beta[, 1], data$beta)

```
