// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// polyseries_mean_single
double polyseries_mean_single(int size, double alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_mean_single(SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_mean_single(size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// polyseries_var_single
double polyseries_var_single(int size, double alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_var_single(SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_var_single(size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// polyseries_mean_grid
NumericVector polyseries_mean_grid(NumericVector points_grid, int size, double alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_mean_grid(SEXP points_gridSEXP, SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type points_grid(points_gridSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_mean_grid(points_grid, size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// polyseries_var_grid
NumericVector polyseries_var_grid(NumericVector points_grid, int size, double alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_var_grid(SEXP points_gridSEXP, SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type points_grid(points_gridSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_var_grid(points_grid, size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// polyseries_mean
NumericVector polyseries_mean(NumericVector size, NumericVector alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_mean(SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_mean(size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// polyseries_var
NumericVector polyseries_var(NumericVector size, NumericVector alpha, double sigma);
RcppExport SEXP _HubbellGLM_polyseries_var(SEXP sizeSEXP, SEXP alphaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(polyseries_var(size, alpha, sigma));
    return rcpp_result_gen;
END_RCPP
}
// DPspecies_cpp
int DPspecies_cpp(double alpha, int size);
RcppExport SEXP _HubbellGLM_DPspecies_cpp(SEXP alphaSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(DPspecies_cpp(alpha, size));
    return rcpp_result_gen;
END_RCPP
}
// lastirling1
arma::vec lastirling1(int n);
RcppExport SEXP _HubbellGLM_lastirling1(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lastirling1(n));
    return rcpp_result_gen;
END_RCPP
}
// lastirlings1
arma::mat lastirlings1(int n);
RcppExport SEXP _HubbellGLM_lastirlings1(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lastirlings1(n));
    return rcpp_result_gen;
END_RCPP
}
// rarefy_C
arma::vec rarefy_C(arma::vec freq, int n, int K, bool verbose);
RcppExport SEXP _HubbellGLM_rarefy_C(SEXP freqSEXP, SEXP nSEXP, SEXP KSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rarefy_C(freq, n, K, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HubbellGLM_polyseries_mean_single", (DL_FUNC) &_HubbellGLM_polyseries_mean_single, 3},
    {"_HubbellGLM_polyseries_var_single", (DL_FUNC) &_HubbellGLM_polyseries_var_single, 3},
    {"_HubbellGLM_polyseries_mean_grid", (DL_FUNC) &_HubbellGLM_polyseries_mean_grid, 4},
    {"_HubbellGLM_polyseries_var_grid", (DL_FUNC) &_HubbellGLM_polyseries_var_grid, 4},
    {"_HubbellGLM_polyseries_mean", (DL_FUNC) &_HubbellGLM_polyseries_mean, 3},
    {"_HubbellGLM_polyseries_var", (DL_FUNC) &_HubbellGLM_polyseries_var, 3},
    {"_HubbellGLM_DPspecies_cpp", (DL_FUNC) &_HubbellGLM_DPspecies_cpp, 2},
    {"_HubbellGLM_lastirling1", (DL_FUNC) &_HubbellGLM_lastirling1, 1},
    {"_HubbellGLM_lastirlings1", (DL_FUNC) &_HubbellGLM_lastirlings1, 1},
    {"_HubbellGLM_rarefy_C", (DL_FUNC) &_HubbellGLM_rarefy_C, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HubbellGLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
